# Secure HBase credentials, core-site.xml and hbase-site.xml are expected to be in the classpath
# It's used for secure HBase only and ignored otherwise
# principal: omid_hbase_client
# keytab: /path/to/hbase/client/keytab

omidClientConfiguration: !!org.apache.omid.tso.client.OmidClientConfiguration
    connectionString: "localhost:54758"

metrics: !!org.apache.omid.metrics.CodahaleMetricsProvider [
    !!org.apache.omid.metrics.CodahaleMetricsConfig {
        outputFreqInSecs: 1,
        reporters: !!set {
            !!org.apache.omid.metrics.CodahaleMetricsConfig$Reporter CSV,
            !!org.apache.omid.metrics.CodahaleMetricsConfig$Reporter CONSOLE
            },
        csvDir: "csvMetrics",
        prefix: "somePrefix",
      }
]

