# =====================================================================================================================
# TSO Server Benchmark Configuration
# =====================================================================================================================

# Benchmark run length (Time Value: >  mins)
benchmarkRunLengthInMins: 5

# Number of simultaneous Omid TSO clients (TxRunners)
txRunners: 1

# Tx requests that each TxRunner triggers per second. Represents the max number of outstanding begin Tx async messages
# in the communication channel
txRateInRequestPerSecond: 100

# Warm up time till the TxRunner reaches the specified transaction rate
warmUpPeriodInSecs: 30

# Writeset cell id generation distribution. Options:
# 1) org.apache.omid.benchmarks.utils.UniformGenerator [ ]
# 2) org.apache.omid.benchmarks.utils.ZipfianGenerator [ max_items_as_long_(e.g._Long.MAX_VALUE) ]
# 3) org.apache.omid.benchmarks.utils.ScrambledZipfianGenerator [ max_items_as_long_(e.g._Long.MAX_VALUE) ]
cellIdGenerator: !!org.apache.omid.benchmarks.utils.UniformGenerator [ ]

# Size of tx writesets in terms of number of modified cells
writesetSize: 2
# If true, the writeset size will be exactly the number specified in the writesetSize config param.
# If false, the writeset size will be homogeneously distributed between 1 & the number specified in writesetSize.
fixedWritesetSize: true

# % of read-only tx triggered -> [ 0 - 100 ] %
percentageOfReadOnlyTxs: 0

# Simulated delay between acquiring timestamp and committing. Can be used to simulated business operation execution.
commitDelayInMs: 0

# ---------------------------------------------------------------------------------------------------------------------
# HBase security configuration
# ---------------------------------------------------------------------------------------------------------------------
# It's used for secure HBase only and ignored otherwise. core-site.xml and hbase-site.xml files are expected to be
# found in the classpath if security is needed. Uncomment and configure the following lines if required:
# principal: omid_hbase_user
# keytab: /path/to/hbase/user/keytab

# ---------------------------------------------------------------------------------------------------------------------
# Omid TSO Client configuration
# ---------------------------------------------------------------------------------------------------------------------
omidClientConfiguration: !!org.apache.omid.tso.client.OmidClientConfiguration
    connectionType: !!org.apache.omid.tso.client.OmidClientConfiguration$ConnType DIRECT
    connectionString: "localhost:54758"

# ---------------------------------------------------------------------------------------------------------------------
# Commit Table storage configuration
# ---------------------------------------------------------------------------------------------------------------------
commitTableStoreModule: !!org.apache.omid.committable.hbase.DefaultHBaseCommitTableStorageModule
    tableName: "OMID_COMMIT_TABLE"

# ---------------------------------------------------------------------------------------------------------------------
# Metrics configuration
# ---------------------------------------------------------------------------------------------------------------------
metrics: !!org.apache.omid.metrics.CodahaleMetricsProvider [
    !!org.apache.omid.metrics.CodahaleMetricsConfig {
        outputFreqInSecs: 10,
        reporters: !!set {
            !!org.apache.omid.metrics.CodahaleMetricsConfig$Reporter CSV,
        },
        csvDir: "csvMetrics",
      }
]